<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vichu-PC" name="week2.day2.testcases.DuplicateLeadFramework" tests="1" failures="0" timestamp="26 May 2018 04:02:30 GMT" time="115.959" errors="1">
  <testcase name="call" time="115.959" classname="week2.day2.testcases.DuplicateLeadFramework">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at week2.day2.wdMethods.SeMethods.locateElement(SeMethods.java:114)
at week2.day2.testcases.DuplicateLeadFramework.call(DuplicateLeadFramework.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- call -->
</testsuite> <!-- week2.day2.testcases.DuplicateLeadFramework -->
